# Generated by Django 5.2.17 on 2026-08-06 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock/Equity'), ('crypto', 'Cryptocurrency'), ('mutual_fund', 'Mutual Fund'), ('fixed_deposit', 'Fixed Deposit'), ('real_estate', 'Real Estate'), ('other', 'Other')], default='other', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('average_buy_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'investment_assets',
            },
        ),
        migrations.CreateModel(
            name='InvestmentPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(default='My Portfolio', max_length=100)),
            ],
            options={
                'db_table': 'investment_portfolios',
            },
        ),
    ]
