# Generated by Django 5.2.17 on 2026-08-06 07:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementMappingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('date_column', models.CharField(max_length=50)),
                ('description_column', models.CharField(max_length=50)),
                ('amount_column', models.CharField(blank=True, help_text='If amounts are in a single column', max_length=50)),
                ('debit_column', models.CharField(blank=True, max_length=50)),
                ('credit_column', models.CharField(blank=True, max_length=50)),
                ('date_format', models.CharField(default='%d/%m/%Y', max_length=50)),
                ('is_global', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'statement_mapping_rules',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('file', models.FileField(upload_to='statements/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('transactions_imported', models.IntegerField(default=0)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='accounts.account')),
            ],
            options={
                'db_table': 'statements',
                'ordering': ['-created_at'],
            },
        ),
    ]
