# Generated by Django 5.2.17 on 2026-09-19 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('statements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Filled automatically when a smart PDF import detects/creates the account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='accounts.account'),
        ),
    ]
