# Generated by Django 5.2.17 on 2026-08-06 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(help_text="Display name, e.g. 'HDFC Savings'", max_length=200)),
                ('account_type', models.CharField(choices=[('bank_account', 'Bank Account'), ('credit_card', 'Credit Card'), ('wallet', 'Wallet'), ('cash', 'Cash'), ('upi', 'UPI')], db_index=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_number_encrypted', models.TextField(blank=True, help_text='Encrypted account/card number')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit (for credit cards only)', max_digits=15, null=True)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color for UI display', max_length=7)),
                ('icon', models.CharField(default='wallet', help_text='Lucide icon name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default account for new transactions')),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
    ]
