# Generated by Django 5.2.17 on 2026-09-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='statement_password_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted PDF statement password for this account (never returned in API).'),
        ),
    ]
