# Generated by Django 5.2.17 on 2026-08-06 07:54

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer'), ('refund', 'Refund'), ('investment', 'Investment'), ('loan_payment', 'Loan Payment'), ('emi', 'EMI'), ('recurring_expense', 'Recurring Expense'), ('recurring_income', 'Recurring Income')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, help_text="Exchange rate to user's default currency at transaction time", max_digits=15)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('merchant_name', models.CharField(blank=True, db_index=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('net_banking', 'Net Banking'), ('wallet', 'Wallet'), ('auto_debit', 'Auto Debit'), ('cheque', 'Cheque'), ('other', 'Other')], default='other', max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('statement_import', 'Statement Import'), ('recurring', 'Recurring'), ('api', 'API')], default='manual', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('statement_reference', models.CharField(blank=True, help_text='Reference from bank statement for dedup', max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categories.category')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
