# Generated by Django 5.2.17 on 2026-08-06 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for system (default) categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'category_type'], name='categories_user_id_4bbd72_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_system'], name='categories_is_syst_2704b6_idx'),
        ),
    ]
