# Generated by Django 5.2.17 on 2026-08-06 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMIPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('principal_component', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_component', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'emi_payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('loan_type', models.CharField(choices=[('home', 'Home Loan'), ('car', 'Car Loan'), ('personal', 'Personal Loan'), ('education', 'Education Loan'), ('other', 'Other')], default='other', max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate in %', max_digits=5)),
                ('tenure_months', models.IntegerField()),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid_off', 'Paid Off'), ('defaulted', 'Defaulted')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-created_at'],
            },
        ),
    ]
